name: jPetStore webApplication
 
inputs:
  NEOLOADWEB_TOKEN   :
    required: true
  ACTION:
    required: true
 
runs:
  using: 'composite'
  steps:
    - name: check action
      id: action
      run: |
        if [ $ACTION == 'smoke_stage' ]; then
          echo "as_code_yml=custom-resources/yaml/stage_smoke_${{ env.NAME }}.yaml" >> $GITHUB_ENV
          echo "scenario=scenario" >> $GITHUB_ENV
        elif [ $ACTION == 'load_stage' ]; then
          echo "as_code_yml=custom-resources/yaml/stage_load_${{ env.NAME }}.yaml" >> $GITHUB_ENV
          echo "scenario=scenario" >> $GITHUB_ENV         
        else
          echo "no ascode"
          echo "scenario=scenario" >> $GITHUB_ENV
        fi
      shell: bash
 
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash
 
    - name: execute action
      uses: arjunsingh-dl/neoload_CICD_web_jpetStore/actions@v0.08 
      env:
        NEOLOADWEB_TOKEN: ${{ env.NEOLOADWEB_TOKEN}}
        AS_CODE: ${{ env.as_code_yml }}
        SCRIPT_REPO:  ${{ github.action }}
        REPO_REF: master
        TEST_NAME: ${{ env.NAME }}_${{ env.ACTION }}_Rel${{ env.RELEASE }}_${{ steps.date.outputs.date }}_${{ github.run_number }}
      shell: bash
