name: LoadTest_PetStore_New
on: 
  workflow_dispatch:
jobs:
  action_cicd:
    environment: stage
    name: LoadTest_PetStore
    runs-on: [ubuntu-latest]
    steps: 
    
      - name: execute action 
        uses: arjunsingh-dl/neoload_CICD_web_jpetStore/actions@v0.08    
        env:
          NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN}}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          NAME: LoadTest_PetStore
          ACTION: smoke_stage
          RELEASE: latest