name: LoadTest_PetStore
on:
  workflow_dispatch:
jobs:
  action_cicd:
    environment: stage
    name: LoadTest_PetStore
    runs-on: [on-prem, self-hosted, Linux]
    steps:
      - name: execute action
        uses: arjunsingh-dl/neoload_CICD_web_jpetStore/actions  
        env:
          NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN}}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          NAME: LoadTest_PetStore
          ACTION: smoke_stage
          RELEASE: latest
          WEBHOOK: ${{ secrets.WEBHOOK }}