name: LoadTest_PetStore
on:
  workflow_dispatch:
  #   this is comment......
  #push:
    #branches: [ develop ]
 
jobs:
  test:
    environment: STAGE
    name: LoadTest_PetStore
    runs-on: [ubuntu-latest]
 
    steps:
 
      - name: Set Splunk Variables
        env:
          GITHUB_TRIGGER: ${{ toJson(github.event_name) }}
          REPO_NAME: ${{ toJson(github.event.repository.name) }}
        id: Splunk
        if: always()
        run: |
          GitTrig=`echo $GITHUB_TRIGGER | tr -d '"'`
          RepoName=`echo $REPO_NAME | tr -d '"'`
          echo "Workspace=Retail Sales Services \n" >> $GITHUB_OUTPUT
          echo "Program=NGPOS \n" >> $GITHUB_OUTPUT
          echo "Service=RSS \n" >> $GITHUB_OUTPUT
          echo "Testtype=LoadTest \n" >> $GITHUB_OUTPUT
          echo "TriggerType=$GitTrig \n" >> $GITHUB_OUTPUT
          echo "RepoName=$RepoName \n" >> $GITHUB_OUTPUT
 
      - name: GetTestStartTime
        id: StartTime
        if: always()
        run: |
          echo "vStartTime=$(date +'%s000')" >> $GITHUB_OUTPUT
          echo "sStartTime=$(date +'%s')" >> $GITHUB_OUTPUT
 
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
 
 
      - name: Load Test for RSS
        uses: arjunsingh-dl/Main
        env:
          NEOLOADWEB_URL: 'https://neoload.saas.neotys.com/'
          WORKSPACE: 'Default Workspace'
          NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN }}
          ZONEID: 'EUGGCP'
          NUM_GENS: 1
          SCENARIO: LoadTest_PetStore
          AS_CODE: 'custom-resources/yaml/LoadTest_PetStore.yaml'
          TEST: New
          TEST_NAME: Load_jPetStore_CICD-PerfTest_${{ steps.date.outputs.date }}_${{ github.run_number }}
 
      - name: Success - Test
        id: Status
        if: ${{ success() }}
        run: |
         echo "TestStatus=Passed \n" >> $GITHUB_OUTPUT
      - name: Failure - Test
        id: StatusFailure
        if: ${{ failure() }}
        run: |
         echo "TestStatus=Failed \n" >> $GITHUB_OUTPUT
      - name: GetTestEndTime
        id: EndTime
        if: always()
        run: |
          echo "vEndTime=$(date +'%s000')" >> $GITHUB_OUTPUT
          echo "sEndTime=$(date +'%s')" >> $GITHUB_OUTPUT