name: LoadTest_PetStore
on:
  workflow_dispatch:
 
jobs:
  test:
    environment: STAGE
    name: LoadTest_PetStore
    runs-on: [windows-latest]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
 
      - name: Load Test for Petstore
        uses: arjunsingh-dl/Main@v0.02
        env:
          NEOLOADWEB_URL: 'https://neoload-api.saas.neotys.com/'
          WORKSPACE: 'Default Workspace'
          NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN}}
          ZONEID: 'APSAWS'
          NUM_GENS: 1
          SCENARIO: LoadTest_PetStore
          AS_CODE: 'custom-resources/yaml/LoadTest_PetStore.yaml'
          TEST: New
          TEST_NAME: Load_CICD_jPetStore_10User_${{ steps.date.outputs.date }}_${{ github.run_number }}
          
      - name: Success - Test
        id: Status
        if: ${{ success() }}
        run: |
          echo "TestStatus=Passed \n" >> $GITHUB_OUTPUT
          # Fetch the latest test result from Neoload Web
          response=$(curl -X 'GET' \
  'https://neoload-api.saas.neotys.com/v3/workspaces/${{ secrets.WORKSPACE_ID }}/test-results?limit=50&offset=0' \
  -H 'accept: application/json' \
  -H 'accountToken: ${{ secrets.NEOLOADWEB_TOKEN }}')
          # Store the response in a file
            echo "$response" > response.json
 
      - name: Extract First Record ID
        id: extract-first-record-id
        run: |
          # Extract the first record's id from the JSON response
          Test_Result_Id=$(jq -r '.[0].id' response.json)
          # Save the first record's id to the environment variable
          echo "Test_Result_Id=$Test_Result_Id" >> $GITHUB_ENV  
 
      - name: Download Test Result
        id: fetch-record-link
        run: |
          # Access the first record's id from the environment variable
          first_record_id="${{ env.Test_Result_Id }}"
          # Use the record ID in another curl command to get the link
          response=$(curl -o /tmp/record.pdf -X POST "https://neoload-api.saas.neotys.com/v3/workspaces/${{ secrets.WORKSPACE_ID }}/test-results/$first_record_id/report" -H "accept: application/pdf" -H "accountToken: ${{ secrets.NEOLOADWEB_TOKEN }}" -H "Content-Type: application/json" -d "{\"language\":\"en\",\"timeZone\":\"Europe/Paris\"}");
          # Store the response in a file
          echo "$response" > response.json
 
      - name: Check Downloaded PDF
        run: |
          # Check if the PDF was downloaded successfully
          if [ -f /tmp/record.pdf ]; then
            echo "PDF downloaded successfully."
          else
            echo "Failed to download PDF."
            exit 1
          fi
 
      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: record
          path: /tmp/record.pdf
 
      - name: Failure - Test
        id: StatusFailure
        if: ${{ failure() }}
        run: |
          echo "TestStatus=Failed \n" >> $GITHUB_OUTPUT
 
 
      - name: GetTestEndTime
        id: EndTime
        if: always()
        run: |
          echo "vEndTime=$(date +'%s000')" >> $GITHUB_OUTPUT
          echo "sEndTime=$(date +'%s')" >> $GITHUB_OUTPUT