name: LoadTest_PetStore
on:
  workflow_dispatch:
  #   this is comment......
  #push:
    #branches: [ develop ]
 
jobs:
  test:
    environment: STAGE
    name: LoadTest_PetStore
    runs-on: [ubuntu-latest]
 
    steps:
 
      - name: Load Test for RSS
        uses: arjunsingh-dl/neoload_CICD_web_jpetStore@v0.08
        env:
          NEOLOADWEB_URL: 'https://neoload.saas.neotys.com/'
          WORKSPACE: 'Default Workspace'
          NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN}}
          ZONEID: 'EUGGCP'
          NUM_GENS: 1
          SCENARIO: LoadTest_PetStore
          AS_CODE: 'custom-resources/yaml/LoadTest_PetStore.yaml'
          TEST: New
          TEST_NAME: Load_jPetStore_CICD-PerfTest