name: LoadTest_PetStore
on:
  workflow_dispatch:
  
 
jobs:
  test:
    environment: STAGE
    name: LoadTest_PetStore
    runs-on: [windows-latest]
 
    steps:
 
      - name: GetTestStartTime
        id: StartTime
        if: always()
        run: |
          echo "vStartTime=$(date +'%s000')" >> $GITHUB_OUTPUT
          echo "sStartTime=$(date +'%s')" >> $GITHUB_OUTPUT
 
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
 
    
      - name: Load Test for Petstore
        uses: arjunsingh-dl/Main@v0.02
        env:
          NEOLOADWEB_URL: 'https://neoload-api.saas.neotys.com/'
          WORKSPACE: 'Default Workspace'
          NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN}}
          ZONEID: 'APSAWS'
          NUM_GENS: 1
          SCENARIO: LoadTest_PetStore
          AS_CODE: 'custom-resources/yaml/LoadTest_PetStore.yaml'
          TEST: New
          TEST_NAME: Load_CICD_jPetStore_10User_${{ steps.date.outputs.date }}_${{ github.run_number }}
 
      - name: Success - Test
        id: Status
        if: ${{ success() }}
        run: |
          echo "TestStatus=Passed \n" >> $GITHUB_OUTPUT
 
      - name: Failure - Test
        id: StatusFailure
        if: ${{ failure() }}
        run: |
          echo "TestStatus=Failed \n" >> $GITHUB_OUTPUT
 
      - name: GetTestEndTime
        id: EndTime
        if: always()
        run: |
          echo "vEndTime=$(date +'%s000')" >> $GITHUB_OUTPUT
          echo "sEndTime=$(date +'%s')" >> $GITHUB_OUTPUT